import JSZip from "jszip";
import type { UmlClassNode } from "../features/diagram/types/diagram.types";
import { JavaGeneratorService } from "./javaGenerator.service"; 

interface ProjectConfig {
  projectName: string;
  groupId: string;
  artifactId: string;
  packageName: string;
  nodes: UmlClassNode[];
  javaVersion: string;
  buildTool: "maven" | "gradle";
}

export class ProjectZipperService {
  
  static async generateAndDownloadZip(config: ProjectConfig) {
    const zip = new JSZip();
    
    const packagePath = config.packageName.replace(/\./g, "/");
    const srcFolder = zip.folder(`src/main/java/${packagePath}`);
    
    if (!srcFolder) throw new Error("Could not create folder structure");

    config.nodes.forEach(node => {
      let javaCode = JavaGeneratorService.generate(node);
      const packageDeclaration = `package ${config.packageName};\n\n`;
      javaCode = packageDeclaration + javaCode;
      srcFolder.file(`${node.data.label}.java`, javaCode);
    });

    const mainContent = `package ${config.packageName};

public class Main {
    public static void main(String[] args) {
        System.out.println("🚀 Project '${config.projectName}' generated by LibreUML is running!");
        
        // TODO: Instantiate your classes here to test them
        // Example: 
        // Usuario user = new Usuario();
        // System.out.println("User created successfully");
    }
}`;
    srcFolder.file("Main.java", mainContent);

    const readmeContent = `# ${config.projectName}\n\nGenerated by LibreUML.\n\n## Specs\n- **Java:** ${config.javaVersion}\n- **Build System:** ${config.buildTool === 'maven' ? 'Maven' : 'Gradle'}\n- **Package:** ${config.packageName}\n\n## How to run\n${config.buildTool === 'maven' ? '`mvn clean install exec:java`' : '`./gradlew run`'}`;
    zip.file("README.md", readmeContent);

    if (config.buildTool === 'maven') {
      zip.file("pom.xml", this.generatePomXml(config));
    } else {
      zip.file("build.gradle", this.generateBuildGradle(config));
      zip.file("settings.gradle", `rootProject.name = '${config.projectName}'`);
    }

    if (window.electronAPI?.isElectron()) {
       const content = await zip.generateAsync({ type: "base64" });
       await window.electronAPI.saveFile(
           content, 
           undefined, 
           `${config.projectName}.zip`, 
           ['zip'], 
           true
       );
    } else {
       const blob = await zip.generateAsync({ type: "blob" });
       const url = URL.createObjectURL(blob);
       const a = document.createElement("a");
       a.href = url;
       a.download = `${config.projectName}.zip`;
       a.click();
       URL.revokeObjectURL(url);
    }
  }

  private static generatePomXml(config: ProjectConfig): string {
    return `<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>${config.groupId}</groupId>
    <artifactId>${config.artifactId}</artifactId>
    <version>1.0.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>${config.javaVersion}</maven.compiler.source>
        <maven.compiler.target>${config.javaVersion}</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
    
    <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>3.1.0</version>
                <configuration>
                    <mainClass>${config.packageName}.Main</mainClass>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>`;
  }

  private static generateBuildGradle(config: ProjectConfig): string {
    return `plugins {
    id 'java'
    id 'application'
}

group = '${config.groupId}'
version = '1.0.0-SNAPSHOT'

repositories {
    mavenCentral()
}

application {
    mainClass = '${config.packageName}.Main'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(${config.javaVersion})
    }
}`;
  }
}