import JSZip from "jszip";
import type { DomainNode } from "../core/domain/models/nodes";
import type { DomainEdge } from "../core/domain/models/edges";
import { JavaGeneratorService } from "./javaGenerator.service"; 

interface ProjectConfig {
  projectName: string;
  groupId: string;
  artifactId: string;
  packageName: string;
  nodes: DomainNode[];     
  allNodes: DomainNode[];  
  edges: DomainEdge[];        
  javaVersion: string;
  buildTool: "maven" | "gradle";
}

export class ProjectZipperService {
  
  static async generateAndDownloadZip(config: ProjectConfig) {
    const zip = new JSZip();
    
    // Create base source folder
    const srcBaseFolder = zip.folder("src/main/java");
    if (!srcBaseFolder) throw new Error("Could not create source folder structure");

    // Track package statistics for README
    const packageStats = new Map<string, number>();

    // Process each node and place in correct package folder
    config.nodes.forEach(node => {
      // Skip NOTE nodes
      if (node.type === 'NOTE') return;
      
      // Determine the package for this class
      const nodePackage = ('package' in node && node.package) ? node.package : config.packageName;
      
      // Track package statistics
      packageStats.set(nodePackage, (packageStats.get(nodePackage) || 0) + 1);
      
      // Generate Java code with auto-resolved imports
      let javaCode = JavaGeneratorService.generate(node, config.allNodes, config.edges);
      
      // Resolve and inject cross-package imports
      const imports = this.resolveImports(node, config.allNodes);
      javaCode = this.injectImports(javaCode, imports);
      
      // Create package folder path
      const packagePath = nodePackage.replace(/\./g, "/");
      const targetFolder = srcBaseFolder.folder(packagePath);
      
      if (!targetFolder) throw new Error(`Could not create folder for package: ${nodePackage}`);
      
      // Get node name
      const nodeName = 'name' in node ? node.name : 'UnknownClass';
      targetFolder.file(`${nodeName}.java`, javaCode);
    });

    // Generate Main.java in the base package
    const mainPackagePath = config.packageName.replace(/\./g, "/");
    const mainFolder = srcBaseFolder.folder(mainPackagePath);
    
    if (mainFolder) {
      const mainContent = `package ${config.packageName};

public class Main {
    public static void main(String[] args) {
        System.out.println("🚀 Project '${config.projectName}' generated by LibreUML is running!");
        
        // TODO: Instantiate your classes here to test them
        // Example: 
        // Usuario user = new Usuario();
        // System.out.println("User created successfully");
    }
}`;
      mainFolder.file("Main.java", mainContent);
    }

    // Generate enhanced README with statistics
    const readmeContent = this.generateReadme(config, packageStats);
    zip.file("README.md", readmeContent);

    if (config.buildTool === 'maven') {
      zip.file("pom.xml", this.generatePomXml(config));
    } else {
      zip.file("build.gradle", this.generateBuildGradle(config));
      zip.file("settings.gradle", `rootProject.name = '${config.projectName}'`);
    }

    if (window.electronAPI?.isElectron()) {
       const content = await zip.generateAsync({ type: "base64" });
       await window.electronAPI.saveFile(
           content, 
           undefined, 
           `${config.projectName}.zip`, 
           ['zip'], 
           true
       );
    } else {
       const blob = await zip.generateAsync({ type: "blob" });
       const url = URL.createObjectURL(blob);
       const a = document.createElement("a");
       a.href = url;
       a.download = `${config.projectName}.zip`;
       a.click();
       URL.revokeObjectURL(url);
    }
  }

  private static generatePomXml(config: ProjectConfig): string {
    return `<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>${config.groupId}</groupId>
    <artifactId>${config.artifactId}</artifactId>
    <version>1.0.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>${config.javaVersion}</maven.compiler.source>
        <maven.compiler.target>${config.javaVersion}</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
    
    <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>3.1.0</version>
                <configuration>
                    <mainClass>${config.packageName}.Main</mainClass>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>`;
  }

  private static generateBuildGradle(config: ProjectConfig): string {
    return `plugins {
    id 'java'
    id 'application'
}

group = '${config.groupId}'
version = '1.0.0-SNAPSHOT'

repositories {
    mavenCentral()
}

application {
    mainClass = '${config.packageName}.Main'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(${config.javaVersion})
    }
}`;
  }

  /**
   * Resolves cross-package imports for a given class node.
   * Scans attributes, method return types, and method parameters to find references
   * to classes in other packages.
   * 
   * @param targetClass - The class node to resolve imports for
   * @param allNodes - All class nodes in the diagram
   * @returns Array of fully qualified import statements
   */
  private static resolveImports(
    targetClass: DomainNode,
    allNodes: DomainNode[]
  ): string[] {
    const imports = new Set<string>();
    
    // Skip NOTE nodes
    if (targetClass.type === 'NOTE') return [];
    
    const targetPackage = ('package' in targetClass) ? targetClass.package : undefined;
    
    // Helper to extract base type name (removes array brackets and generics)
    const extractTypeName = (type: string): string => {
      return type.replace(/\[\]$/, "").replace(/<.*>/, "").trim();
    };

    // Helper to check if a type needs an import
    const needsImport = (typeName: string, referencedClass: DomainNode): boolean => {
      // Skip primitive types and java.lang classes
      const primitives = ["int", "double", "float", "long", "short", "byte", "boolean", "char", "void"];
      const javaLang = ["String", "Integer", "Double", "Float", "Long", "Short", "Byte", "Boolean", "Character", "Object"];
      
      if (primitives.includes(typeName) || javaLang.includes(typeName)) {
        return false;
      }
      
      // Skip NOTE nodes
      if (referencedClass.type === 'NOTE') {
        return false;
      }
      
      // Skip if no package (default package)
      const refPackage = ('package' in referencedClass) ? referencedClass.package : undefined;
      if (!refPackage) {
        return false;
      }
      
      // Skip if same package
      if (refPackage === targetPackage) {
        return false;
      }
      
      return true;
    };

    // Scan attributes (CLASS and ABSTRACT_CLASS only)
    if ('attributes' in targetClass && targetClass.attributes) {
      targetClass.attributes.forEach(attr => {
        const typeName = extractTypeName(attr.type);
        const referencedClass = allNodes.find(n => 'name' in n && n.name === typeName);
        
        if (referencedClass && needsImport(typeName, referencedClass)) {
          const refPackage = ('package' in referencedClass) ? referencedClass.package : undefined;
          if (refPackage) {
            imports.add(`import ${refPackage}.${typeName};`);
          }
        }
      });
    }

    // Scan methods (return types and parameters)
    if ('methods' in targetClass && targetClass.methods) {
      targetClass.methods.forEach(method => {
        // Check return type
        const returnTypeName = extractTypeName(method.returnType);
        const returnClass = allNodes.find(n => 'name' in n && n.name === returnTypeName);
        
        if (returnClass && needsImport(returnTypeName, returnClass)) {
          const refPackage = ('package' in returnClass) ? returnClass.package : undefined;
          if (refPackage) {
            imports.add(`import ${refPackage}.${returnTypeName};`);
          }
        }
        
        // Check parameters
        if (method.parameters) {
          method.parameters.forEach(param => {
            const paramTypeName = extractTypeName(param.type);
            const paramClass = allNodes.find(n => 'name' in n && n.name === paramTypeName);
            
            if (paramClass && needsImport(paramTypeName, paramClass)) {
              const refPackage = ('package' in paramClass) ? paramClass.package : undefined;
              if (refPackage) {
                imports.add(`import ${refPackage}.${paramTypeName};`);
              }
            }
          });
        }
      });
    }

    return Array.from(imports).sort();
  }

  /**
   * Injects import statements into generated Java code.
   * Places imports after the package declaration and before the class definition.
   * 
   * @param javaCode - The generated Java code
   * @param imports - Array of import statements
   * @returns Java code with imports injected
   */
  private static injectImports(
    javaCode: string,
    imports: string[]
  ): string {
    if (imports.length === 0) {
      return javaCode;
    }

    const lines = javaCode.split("\n");
    const result: string[] = [];
    let packageLineIndex = -1;

    // Find the package declaration line
    for (let i = 0; i < lines.length; i++) {
      if (lines[i].startsWith("package ")) {
        packageLineIndex = i;
        break;
      }
    }

    if (packageLineIndex === -1) {
      // No package declaration, add imports at the top
      result.push(...imports);
      result.push("");
      result.push(...lines);
    } else {
      // Add lines up to and including package declaration
      result.push(...lines.slice(0, packageLineIndex + 1));
      result.push("");
      
      // Add imports
      result.push(...imports);
      result.push("");
      
      // Add remaining lines (skip empty line after package if it exists)
      let startIndex = packageLineIndex + 1;
      if (startIndex < lines.length && lines[startIndex].trim() === "") {
        startIndex++;
      }
      result.push(...lines.slice(startIndex));
    }

    return result.join("\n");
  }

  /**
   * Generates an enhanced README.md with project statistics.
   * 
   * @param config - Project configuration
   * @param packageStats - Map of package names to class counts
   * @returns README content as string
   */
  private static generateReadme(
    config: ProjectConfig,
    packageStats: Map<string, number>
  ): string {
    const lines: string[] = [];
    
    lines.push(`# ${config.projectName}`);
    lines.push("");
    lines.push("Generated by LibreUML - Open Source UML Class Diagram Editor");
    lines.push("");
    
    lines.push("## Project Statistics");
    lines.push("");
    lines.push(`- **Total Classes:** ${config.nodes.length}`);
    lines.push(`- **Total Packages:** ${packageStats.size}`);
    lines.push(`- **Java Version:** ${config.javaVersion}`);
    lines.push(`- **Build System:** ${config.buildTool === 'maven' ? 'Maven' : 'Gradle'}`);
    lines.push("");
    
    if (packageStats.size > 0) {
      lines.push("## Package Structure");
      lines.push("");
      
      const sortedPackages = Array.from(packageStats.entries()).sort((a, b) => 
        a[0].localeCompare(b[0])
      );
      
      sortedPackages.forEach(([pkg, count]) => {
        lines.push(`- \`${pkg}\` - ${count} class${count !== 1 ? "es" : ""}`);
      });
      
      lines.push("");
    }
    
    lines.push("## How to Build & Run");
    lines.push("");
    
    if (config.buildTool === 'maven') {
      lines.push("### Using Maven");
      lines.push("```bash");
      lines.push("# Compile the project");
      lines.push("mvn clean compile");
      lines.push("");
      lines.push("# Run the Main class");
      lines.push("mvn exec:java");
      lines.push("");
      lines.push("# Package as JAR");
      lines.push("mvn package");
      lines.push("```");
    } else {
      lines.push("### Using Gradle");
      lines.push("```bash");
      lines.push("# Compile the project");
      lines.push("./gradlew build");
      lines.push("");
      lines.push("# Run the Main class");
      lines.push("./gradlew run");
      lines.push("");
      lines.push("# Create distribution");
      lines.push("./gradlew distZip");
      lines.push("```");
    }
    
    lines.push("");
    lines.push("## Project Structure");
    lines.push("```");
    lines.push("src/");
    lines.push("└── main/");
    lines.push("    └── java/");
    
    const sortedPackages = Array.from(packageStats.keys()).sort();
    sortedPackages.forEach(pkg => {
      const depth = pkg.split(".").length;
      const indent = "        " + "    ".repeat(depth - 1);
      const pkgName = pkg.split(".").pop();
      lines.push(`${indent}└── ${pkgName}/`);
    });
    
    lines.push("```");
    lines.push("");
    
    lines.push("## Features");
    lines.push("");
    lines.push("- ✅ Proper package hierarchy");
    lines.push("- ✅ Auto-resolved cross-package imports");
    lines.push("- ✅ Inheritance and interface relationships preserved");
    lines.push("- ✅ Maven/Gradle build configuration");
    lines.push("- ✅ Ready to import into any Java IDE");
    lines.push("");
    
    lines.push("## Notes");
    lines.push("");
    lines.push("- All classes include package declarations");
    lines.push("- Method bodies contain placeholder implementations");
    lines.push("- Cross-package imports are automatically resolved");
    lines.push("- You may need to add external dependencies to your build file");
    lines.push("");
    
    lines.push("---");
    lines.push("");
    lines.push("Created with ❤️ using [LibreUML](https://github.com/The-Indigo0218/LibreUML)");
    
    return lines.join("\n");
  }
}