import {
  Box,
  CircleDot,
  BoxSelect,
  StickyNote,
  List,
  ArrowUpRight,
  GitCommitHorizontal,
  ArrowUp,
  MoveRight,
  Diamond,
  User,
  Circle,
  Square,
  ArrowRight,
  FileCode,
  Package,
  Upload,
  Image as ImageIcon,
  FileCode2,
  CornerDownLeft,
  PlusCircle,
  XCircle,
  GitBranch,
  CircleHelp,
  Repeat,
  Columns2,
  ListOrdered,
  ArrowDownNarrowWide,
  Scissors,
  ShieldAlert,
  Ban,
  BadgeCheck,
  EyeOff,
  Eye,
  PersonStanding,
  LogIn,
  LogOut,
  Frame,
  ArrowDownUp,
  Timer,
  Clock,
  Brackets,
} from "lucide-react";

/**
 * Icon mapping for dynamic icon rendering
 * Maps icon names (strings) to Lucide React components
 */
export const iconMap: Record<string, React.ComponentType<{ className?: string }>> = {
  Box,
  CircleDot,
  BoxSelect,
  StickyNote,
  List,
  ArrowUpRight,
  GitCommitHorizontal,
  ArrowUp,
  MoveRight,
  Diamond,
  User,
  Circle,
  Square,
  ArrowRight,
  FileCode,
  Package,
  Upload,
  ImageIcon,
  FileCode2,
  CornerDownLeft,
  PlusCircle,
  XCircle,
  GitBranch,
  CircleHelp,
  Repeat,
  Columns2,
  ListOrdered,
  ArrowDownNarrowWide,
  Scissors,
  ShieldAlert,
  Ban,
  BadgeCheck,
  EyeOff,
  Eye,
  PersonStanding,
  LogIn,
  LogOut,
  Frame,
  ArrowDownUp,
  Timer,
  Clock,
  Brackets,
};

/**
 * Get icon component by name
 */
export function getIconComponent(iconName: string): React.ComponentType<{ className?: string }> | null {
  return iconMap[iconName] || null;
}
